import Space from "../../../Space"
async function Sticker(ctx) {
  if (Space.Helpers.RandomNum(1, 100) <= 15) {
    if (ctx.message.sticker.emoji in MyStickerSet) {
      return ctx.replyWithSticker(MyStickerSet[ctx.message.sticker.emoji]);
    } else if (ctx.message.sticker.emoji in CatStickerSet) {
      return ctx.replyWithSticker(CatStickerSet[ctx.message.sticker.emoji]);
    }
  }
}

export default Sticker;

let CatStickerSet = {
  "😂": "CAACAgIAAxkBAAIDwmECSdghggbmH3T5MVEB-VqNrslNAAJuDAAC32wZSkdZVXyKLr_DIAQ",
  "😘": "CAACAgIAAxkBAAIDxGECSiFHUGhrFDiKhwUCqs87PdOPAAK7EgACaBDZSfrl-N3-SLTXIAQ",
  "👍": "CAACAgIAAxkBAAIDxmECSmc35-732rax0IVhzd4dk1lHAAJ1DwACvScRSgNCdFZ_RgthIAQ",
  "😨": "CAACAgIAAxkBAAIDyGECSoz67eslcCcIPFud5KSv14lOAAJzEAACqOgRSmKIrKBCdwtTIAQ",
  "👋": "CAACAgIAAxkBAAIDymECSqgn-nb4AAGvk3BETtk2qaHTkAACsAwAAtXO2EkYBH8D8PsM3yAE",
  "☺️": "CAACAgIAAxkBAAIDzGECSt2o_VYqi7fpUTuedsTN2vfBAAIGDQACXicZSiFZnpokFU0ZIAQ",
  "⏰": "CAACAgIAAxkBAAIDzmECSwABA7BZusAX7VDE5arqsdAEYwACSg8AAmCm0EndM-7edjWcqyAE",
  "❓": "CAACAgIAAxkBAAID0GECSyQyPuaguDq2iwkDY4pd03KRAAI6DwACbKXZSQ009lztSI28IAQ",
  "❤️": "CAACAgIAAxkBAAID0mECS0eP51eJIwQyZhDX_w8QN5t7AAIvDwACQK7RSenf83DveI7CIAQ",
  "✨": "CAACAgIAAxkBAAID1GECS2Jf58rtbHdO3MbrznVaMjYcAAL1DAACt1zZSR8FnNZCmxcqIAQ",
  "🥳": "CAACAgIAAxkBAAID1mECS3mmS9H8Jh0zFGx6IOVglE7pAAIbDAAC9HEYSnK9-WcXPPVOIAQ",
  "😴": "CAACAgIAAxkBAAID2GECS61jqMvmXRW1AAHNgqD9SNnpmwACygoAAlc5GUp5BxzBROgsySAE",
  "💐": "CAACAgIAAxkBAAID2mECS8czsf9hm7C_9BIn2fmwG3-nAAKaDgACczkQSlbFLctyG1jRIAQ",
  "🤡": "CAACAgIAAxkBAAID3GECS_Np8sjymAwgvQFqaJfM21RSAAL9DQACNqwRSp0c2t2iUz8kIAQ",
  "💪": "CAACAgIAAxkBAAID32ECTBc8Q2TB5WCGf0BLJKDliYaAAAIeDwAC3L8RSi_XlinDNYQAASAE",
  "😠": "CAACAgIAAxkBAAID4WECTCxlXMChklpwWuWjQ_ohwOh_AALaEAAC96sYSrPsgGDfs6wlIAQ",
  "🚶‍♂️": "CAACAgIAAxkBAAID42ECTEPp2BWkXqvIporrov5HeOImAAIKCgACnhIZSlUq1Ym0T3kYIAQ",
  "🥵": "CAACAgIAAxkBAAID5WECTFfbH3p4jhiZY_sabsQDU333AAJcCwACqBUYShcj0M67Mj6nIAQ",
  "😟": "CAACAgIAAxkBAAID52ECTG4lCQdAifGUeCOU8wABh9hNHAACnA0AAj3FGEp68CI2ZWSumCAE",
  "😡": "CAACAgIAAxkBAAID6WECTIecya51n-V3s0VphLCySCKFAAJdEAACqoYRSnLCLNZ2_FluIAQ",
  "🍿": "CAACAgIAAxkBAAID62ECTKl84_vrpinrBkQ-obVlvh_uAAJGDQAC3MRpStjhudGyNjNwIAQ",
  "😑": "CAACAgIAAxkBAAID7WECTLw4PD3qPL2nsXHTZS8PN36MAALUDwAC2WZpSgVriX5OZGvqIAQ",
  "😭": "CAACAgIAAxkBAAID72ECTNFRX23u08brUxT8-lpE6ApRAAJsDgACe1NoStT3thanGmnIIAQ",
  "🤯": "CAACAgIAAxkBAAID82ECTQABqhsjlOQE1Q9444xn6BrRVgAC2xMAAghcaUrxIfu233UEHSAE",
  "🤷": "CAACAgIAAxkBAAID9WECTS4ybWydHinFkfsHns8jT7c_AALRDAACovthSgcRPxdEzhvCIAQ",
}

let MyStickerSet = {
  "😶": "CAACAgUAAxkBAAPMYXNjdyQUv1J8MG6Wd-O2it7HBy4AAiADAAL9RkFW04AtW309YokhBA",
  "😴": "CAACAgUAAxkBAAPGYXNjSeAhycXOF1KnpWlkZ8fPaRwAAgoEAAJos0hWiy9SKdJOSpkhBA",
  "😭": "CAACAgUAAxkBAAOyYXNiUitDBD6cZYTD2uGwtWLlHwoAAhUEAAIfTUhWbjPffbd8cBIhBA",
  "😀": "CAACAgUAAxkBAAO0YXNiYqRUYc_Yo_jn5V5mq59xWecAAuICAAJrZaFWci91HAmEn60hBA",
  "🥰": "CAACAgUAAxkBAAPiYXNkdPyLi7NOMdlLthkpT7mLUp4AAtYDAAJSZ0BWv-rBVNx5iv4hBA",
  "😊": "CAACAgUAAxkBAAO6YXNirbUQh0QV2QOhZIu5cukVe-IAAr0DAALQakhWUC1VhoPd69YhBA",
  "😝": "CAACAgUAAxkBAAO8YXNixmd5SlulzQYVzVE_3XPVcIQAAqEDAAKPI0FWnW_zfo9HTMAhBA",
  "😨": "CAACAgUAAxkBAAO-YXNi4SATu2VxctJfK9pvdjv7ZhUAAkgCAAJunUlWZ-aA3J1PTiohBA",
  "🥱": "CAACAgUAAxkBAAPCYXNjF4kUnELcOiidMEgn6boGfJIAAqYEAAJbcElWX_bcDvIs9b0hBA",
  "😮": "CAACAgUAAxkBAAIBIGFzZ0Te3xWXD33zwVWdeXoTzPrOAAJwAwACK89IVrPDNLIDjsApIQQ",
  "❓": "CAACAgUAAxkBAAPQYXNjtmU30EdEjgYiG9gHdJ7yxPsAArkDAAIgJUlWl6E79EKHkVkhBA",
  "😕": "CAACAgUAAxkBAAPSYXNjzTYDwEts1Bp-_06Af7LpfLgAArMDAAI9tklWzb0xi7RWqechBA",
  "😚": "CAACAgUAAxkBAAPYYXNkBnUrwRmwA0e48XaJ6DrA6JAAAg8EAALRM0hWajsHUbAl4ikhBA",
  "😠": "CAACAgUAAxkBAAPcYXNkL4hdkNhJogUcU-TF06rTlJ0AAmsEAAKZV0hWz6LeUsId15ohBA",
  "🤤": "CAACAgUAAxkBAAPeYXNkQjqhDY0-5zPr0mv6epO9f24AAjEFAAJnZUhWnOehqdPHJtUhBA",
  "😥": "CAACAgUAAxkBAAPgYXNkWbYC5YnV-B7jIpb6KiFD1hEAArYCAALLVkhWPMcSedmEDZQhBA",
  "🤔": "CAACAgUAAxkBAAIBEGFzZnj3jU9xUPYUCg7WbmbHG93FAAK3AgACfC-hVpwxpRV__Tz0IQQ",
  "😑": "CAACAgUAAxkBAAPsYXNk_7UOB6ZnIxsXNkHCxk7bf1QAAsADAAJeEkFWmVWdWxT0OxEhBA",
  "🥺": "CAACAgUAAxkBAAP-YXNleH5BGMybgpwvyc0QFJfUw2IAAlcDAAJEo0BWFri4bZOIYi8hBA",
  "🤗": "CAACAgUAAxkBAAIBAAFhc2WNDJrpRfZkTpdvxf4SGTyzbAACGQQAApVCQVYFN1P7SibLzCEE",
  "😛": "CAACAgUAAxkBAAIBBGFzZapqhPvxKQABek3z2hAn39IeJQACRwIAAibfSFYcqKsbfJkCqiEE",
  "❌": "CAACAgUAAxkBAAIBBmFzZcyG6uY5BSsMHEd9PL2OgjvnAAIkAwACLktIVs3dvlFpLJb3IQQ",
  "❗️": "CAACAgUAAxkBAAIBHGFzZx7XCokhKzuYw7Y6MmL1wxBJAAKgBAACmzNIVrN8dCkbl9rAIQQ",
  "😓": "CAACAgUAAxkBAAIBDmFzZjaVuULtDrHPnmmei9dnlCIyAAKQAgACUgehVv_O-x1lV-ceIQQ",
  "👍": "CAACAgUAAxkBAAIBR2FzbhpaTZ2wxEyZuoR-I_bYrn4VAAKoAANs66IracjsD1fCdqshBA",
  "😱": "CAACAgUAAxkBAAIBS2FzblHUKPgoaL7ojfAXK91-qH0SAALgAANs66IrF2XcMo56ztshBA",
  "🐟": "CAACAgUAAxkBAAIBT2FzbrWHWep67c3jcstCCD1Em1MtAALLAANs66IrPo3FOfRCtzohBA",
  "😁": "CAACAgUAAxkBAAIBUWFzbxN2k0ItxgEeIUyFgRTdqhGvAALxAANs66Irz8uvoLTV5FkhBA",
}