name: Merge conflicts
on:
  push:

jobs:
  triage:
    if: github.repository == 'CoPoKo/Space'
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
